#!/bin/sh

spath=$( cd "$(dirname "$0")" ; pwd -P )

set -e

$spath/device-umount-all

mount | grep debian

if [ -d $spath/debian/proc/1 ]; then
	echo "$spath/debian already exists, please check mount!"
else
	rm -rf $spath && echo "cleanup eadb succeed!"
fi

