name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install qemu-user-static debootstrap
      shell: bash
    - name: build cli
      run: cargo build --release 
    - name: build full image
      run: sudo ./target/release/eadb build --bcc
    - name: build mini image
      run: sudo ./target/release/eadb build
    - name: Get the version
      id: get_tags
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      shell: bash
    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "debianfs-mini.tar.gz,debianfs-full.tar.gz,target/release/eadb"
        body: ${{steps.github_release.outputs.changelog}}
        tag: ${{ steps.get_tags.outputs.VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
