name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install qemu-user-static debootstrap
      shell: bash
    - name: build cli
      run: cargo build --release 
    - name: build full image
      run: sudo ./target/release/eadb build --bcc
    - name: build mini image
      run: sudo ./target/release/eadb build
    - name: Get the version
      id: get_tags
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      shell: bash
    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Write File
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: ./release_notes.txt
        contents: |
          ${{ steps.github_release.outputs.changelog }}
        write-mode: append
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "debianfs-mini.tar.gz,debianfs-full.tar.gz,target/release/eadb"
        bodyFile: "./release_notes.txt"
        token: ${{ secrets.GITHUB_TOKEN }}
